# Generated by Django 6.0.3 on 2026-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(default='0 Years', max_length=50),
        ),
    ]
