# Generated by Django 6.0.3 on 2026-04-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_teacher_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mid Term, Final Exams, Unit Test', max_length=100)),
                ('exam_class', models.CharField(help_text='e.g., Class 10, Class A', max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('holiday_type', models.CharField(choices=[('Public Holiday', 'Public Holiday'), ('School Holiday', 'School Holiday'), ('Term Break', 'Term Break'), ('Exam Break', 'Exam Break')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='e.g., Class 10 A', max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Time Table',
                'verbose_name_plural': 'Time Tables',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
