# Generated by Django 6.0.3 on 2026-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='mOEpAvujv0tses3VDPUpCxMd2ghKq4pj', editable=False, max_length=32, unique=True),
        ),
    ]
