# Generated by Django 6.0.3 on 2026-03-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='kPAv8UJYqpyld9QlNZjmyfn6Z17zYBEJ', editable=False, max_length=32, unique=True),
        ),
    ]
