# Generated by Django 6.0.3 on 2026-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Py6zf7FAuOU0ZXLb9DZuJi6O2lLCuNyb', editable=False, max_length=32, unique=True),
        ),
    ]
