# Generated by Django 6.0.3 on 2026-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='RDrYB8hQwdztwURDJ3wpYhdFlt2GfwzB', editable=False, max_length=32, unique=True),
        ),
    ]
