# Generated by Django 6.0.3 on 2026-03-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='rBQIBKrI78AU2RRfvqQLAU9Wps4lkZZ6', editable=False, max_length=32, unique=True),
        ),
    ]
