# Generated by Django 6.0.3 on 2026-03-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HlqZHtQT8D7w6yr0XVO7TRfNT6dPmn1D', editable=False, max_length=32, unique=True),
        ),
    ]
