# Generated by Django 6.0.3 on 2026-03-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_customuser_is_student_and_more'),
        ('home_auth', '0009_alter_customuser_email_and_more'),
    ]

    operations = [
    ]
