# Generated by Django 6.0.3 on 2026-03-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BmyAouhwmPmMcJXgUmrR3U2DK8Ksm7Fi', editable=False, max_length=32, unique=True),
        ),
    ]
