# Generated by Django 6.0.3 on 2026-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Rv89DU77iet8WOszWRTcN0uhoNioXbIT', editable=False, max_length=32, unique=True),
        ),
    ]
