# Generated by Django 6.0.3 on 2026-04-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_customuser_is_student_and_more'),
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
    ]
