# Generated by Django 6.0.3 on 2026-04-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_merge_20260331_2244'),
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
    ]
