# Generated by Django 6.0.3 on 2026-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0018_merge_20260401_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='loeVqpA99nFPzStcjw6cB4gvWuBheFz1', editable=False, max_length=32, unique=True),
        ),
    ]
