# Generated by Django 6.0.3 on 2026-04-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0018_merge_20260401_1339'),
        ('home_auth', '0019_alter_passwordresetrequest_token'),
    ]

    operations = [
    ]
