# Generated by Django 6.0.3 on 2026-04-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_merge_20260401_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='aSKuGYd3oBWDwl9TUA4BCqnL0PbqUenQ', editable=False, max_length=32, unique=True),
        ),
    ]
