# Generated by Django 6.0.3 on 2026-04-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0025_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3kFW4zyNBJ69H9BT2zwMEJwpcws123eU', editable=False, max_length=32, unique=True),
        ),
    ]
