# Generated by Django 6.0.3 on 2026-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0026_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='YqFXoraYHt1EknySKDvhk5mL4ZRKrB9z', editable=False, max_length=32, unique=True),
        ),
    ]
